apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-gallery-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modern-gallery-green
  template:
    metadata:
      labels:
        app: modern-gallery-green
    spec:
      containers:
      - name: modern-gallery-green
        image: deepanshua04/modern-gallery:latest
        ports:
        - containerPort: 3000
