apiVersion: v1
kind: Service
metadata:
  name: modern-gallery-service
spec:
  selector:
    app: modern-gallery-blue     # ðŸŸ¦ Default traffic â†’ BLUE
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
